### ISSUE TITLE
Empty sampleValue in google conversation action

### ISSUE THREAD

**Issue by acerbisgianluca** [jovotech/jovo-model#17]
The for-loop which contains the following line generates 2 elements: the first one contains a valid sample value taken from the slot type, but the second one is an empty string and google api gives an error.
https://github.com/jovotech/jovo-model/blob/5e68674baca996efadfc3766361e6159212449ff/packages/jovo-model-google/src/JovoModelGoogle.ts#L100

Example:
```
"trainingPhrases":
  - "($name 'clock-tic-tac' auto=true)"
  - "($count '' auto=true)"
```

**Comment by aswetlow** [comment]
thanks @acerbisgianluca 

What's the input phrase here?

cc @rubenaeg

**Comment by acerbisgianluca** [comment]
@aswetlow Oh sorry, I misunderstood the error message. The $count input is a predefined input type (actions.type.Number), so the for loop runs correctly and, for the second input, the sampleValue remains empty, but apparently this isn't a valid value.

**Comment by aswetlow** [comment]
Sorry, I'm a little lost here 😄 Ruben did the integration.

What are you trying to do and what error do you get?

**Comment by acerbisgianluca** [comment]
I have this intent in my Jovo model:
```
{
            "name": "CustomAudioIntent",
            "phrases": [
                "{name}",
                "{count}"
            ],
            "inputs": [
                {
                    "name": "name",
                    "type": "audioNameType",
                    "alexa": {
                        "samples": [
                            "{name}",
                            "voglio {name}"
                        ]
                    }
                },
                {
                    "name": "count",
                    "type": {
                        "alexa": "AMAZON.NUMBER",
                        "googleAssistant": "actions.type.Number"
                    },
                    "alexa": {
                        "samples": [
                            "{count}",
                            "voglio {count}"
                        ]
                    }
                }
            ]
        },
```
and **Jovo build** generates this:
```
"trainingPhrases":
  - "($name 'clock-tic-tac' auto=true)"
  - "($count '' auto=true)"
"parameters":
  - "name": "name"
    "type":
      "name": "audioNameType"
  - "name": "count"
    "type":
      "name": "actions.type.Number"
```
but **jovo deploy -p googleAction** gives me this error:
```
[ERR] Request contains an invalid argument.
 »
 »   Module:   jovo-cli-platform-google-ca
 »   Hint:     Event handler contains function call named 'Jovo' which is not present in the interaction model.
```

**Comment by rubenaeg** [comment]
Hm, this shouldn't happen in the first place. I'll have a look and get back to you once I know more! Thanks for reporting this.

**Comment by acerbisgianluca** [comment]
@rubenaeg Sorry, I pasted the wrong error message for the first case. I've just fixed it.

**Comment by acerbisgianluca** [comment]
Yes, I posted them [here](https://gist.github.com/acerbisgianluca/68b9ec872ea27c82631ecff7f09aa0a9).

**Comment by acerbisgianluca** [comment]
Hy @rubenaeg, I posted them [here](https://gist.github.com/acerbisgianluca/68b9ec872ea27c82631ecff7f09aa0a9).

**Comment by rubenaeg** [comment]
Thanks, I'll have a look!

**Comment by acerbisgianluca** [comment]
@rubenaeg I found the problem. To overwrite the endpoint based on the stage, I added the following code to project.js:
```
googleAction: {
                manifest: {
                    webhooks: {
                        ActionsOnGoogleFulfillment: {
                            httpsEndpoint: {
                                baseUrl: `${process.env.API_GATEWAY_URL}/dev/`,
                            },
                        },
                    },
                },
            },
```
This will output the correct endpoint, but removes
```
handlers:
  - name: Jovo
```
so it is undefined when I try to push the package.

**Comment by rubenaeg** [comment]
Yes, you're correct! This has been addressed and fixed in the newest version, you can update your Jovo CLI using `npm install -g jovo-cli`.

**Comment by acerbisgianluca** [comment]
Nice, I will update. Btw How does Jovo route request? Does it use webhook name or intent name? Should I declare default intent inside the model (main, no match, cancel)?
