### ISSUE TITLE
Google Actions: Disallowed training phrases?

### ISSUE THREAD

**Issue by asarazan** [jovotech/jovo-model#19]
This is a weird one, and maybe something is breaking farther upstream, but I got the following error:

```
{
  "error": {
    "code": 400,
    "message": "Invalid value at 'files.config_files.config_files[27].intent.training_phrases[0]' (TYPE_STRING), true",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "description": "Invalid value at 'files.config_files.config_files[27].intent.training_phrases[0]' (TYPE_STRING), true",
            "field": "files.config_files.config_files[27].intent.training_phrases[0]"
          }
        ]
      }
    ]
  }
}
```

The error resolved when I removed the following training phrases from my intents:
* yes
* no
* off

I have no idea why this is the case :-(

**Comment by rubenaeg** [comment]
Please update your Jovo CLI to the latest version, this was a big with a previous version. .yaml files take values such as "yes" and "no" as boolean, so the gactions CLI validation fails. The newest version of the Jovo CLI fixes this bug.

**Comment by asarazan** [comment]
Has the fix also been applied to `jovo-model`? This bug occurs when using the model lib directly.

**Comment by rubenaeg** [comment]
Not yet, no. I've already implemented this tho, so it should be fixed with the next update.

**Comment by asarazan** [comment]
Great, looking forward to it!

**Comment by aswetlow** [comment]
Updates published last week. Thanks, @asarazan, and @rubenaeg
